# https://github.com/alex-shpak/hugo-book

baseURL = 'https://mukimasta.github.io/'
languageCode = 'zh-CN'
title = 'mukimasta'
theme = 'hugo-book'

enableGitInfo = true

[params]
    BookLogo = 'logo.png'