# https://github.com/alex-shpak/hugo-book

baseURL = 'https://mukimasta.github.io/'
languageCode = 'zh-CN'
title = 'mukimasta'
theme = 'book'

enableGitInfo = true

[params]
    BookRepo = 'https://github.com/mukimasta/mukimasta.github.io'
    BookCommitPath = 'commit'
    BookDateFormat = '06/01/02'
    BookSearch = true
